// <auto-generated />
using DestekApp.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DestekApp.Migrations
{
    [DbContext(typeof(DestekAppDBContext))]
    [Migration("20211224164426_dört")]
    partial class dört
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DestekApp.Models.Kullanıcı", b =>
                {
                    b.Property<int>("KullanıcıID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullanıcıID"), 1L, 1);

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Şifre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KullanıcıID");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanıcılar");

                    b.HasData(
                        new
                        {
                            KullanıcıID = 1,
                            Eposta = "gizem@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 2,
                            Eposta = "ali@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 3,
                            Eposta = "mahmut@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 4,
                            Eposta = "mansur @hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 5,
                            Eposta = "gamze@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 6,
                            Eposta = "miraç@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 7,
                            Eposta = "yücel@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 8,
                            Eposta = "kubilay@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 9,
                            Eposta = "hayati@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 10,
                            Eposta = "bedriye müge@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 11,
                            Eposta = "birsen@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 12,
                            Eposta = "serdal@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 13,
                            Eposta = "bünyamin@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 14,
                            Eposta = "özgür@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 15,
                            Eposta = "ferdi@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 16,
                            Eposta = "reyhan@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 17,
                            Eposta = "ilhan@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 18,
                            Eposta = "gülşah@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 19,
                            Eposta = "nalan@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 20,
                            Eposta = "semih@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 21,
                            Eposta = "ergün@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 22,
                            Eposta = "fatih@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 23,
                            Eposta = "şenay@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 24,
                            Eposta = "serkan@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 25,
                            Eposta = "emre@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 26,
                            Eposta = "peker@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 27,
                            Eposta = "irazca@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 28,
                            Eposta = "hatice@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 29,
                            Eposta = "bariş@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 30,
                            Eposta = "rezan@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 31,
                            Eposta = "fatih@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 32,
                            Eposta = "fuat@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 33,
                            Eposta = "gökhan@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 34,
                            Eposta = "orhan@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 35,
                            Eposta = "mehmet@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 36,
                            Eposta = "evren@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 37,
                            Eposta = "oktay@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 38,
                            Eposta = "harun@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 39,
                            Eposta = "yavuz@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 40,
                            Eposta = "pinar@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 41,
                            Eposta = "mehmet@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 42,
                            Eposta = "umut@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 43,
                            Eposta = "mesude@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 44,
                            Eposta = "seko@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 45,
                            Eposta = "yunus@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 46,
                            Eposta = "eyyup sabri@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 47,
                            Eposta = "umut@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 48,
                            Eposta = "cengiz@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 49,
                            Eposta = "ufuk@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 50,
                            Eposta = "ahmet ali@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 51,
                            Eposta = "mediha@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 52,
                            Eposta = "hasan@outlook.com",
                            RolID = 4,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 53,
                            Eposta = "kamil@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 54,
                            Eposta = "nebi@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 55,
                            Eposta = "özcan@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 56,
                            Eposta = "ilayda@icloud.com",
                            RolID = 3,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 57,
                            Eposta = "ceren@hotmail.com",
                            RolID = 2,
                            Şifre = "123456"
                        },
                        new
                        {
                            KullanıcıID = 58,
                            Eposta = "serkan@gmail.com",
                            RolID = 1,
                            Şifre = "123456"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("RolAdı")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolAdı = "UserCandidate"
                        },
                        new
                        {
                            RolID = 2,
                            RolAdı = "UserNormal"
                        },
                        new
                        {
                            RolID = 3,
                            RolAdı = "Admin"
                        },
                        new
                        {
                            RolID = 4,
                            RolAdı = "Supervisor"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Kullanıcı", b =>
                {
                    b.HasOne("DestekApp.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
